version: '3'
services:
  apache: # change to suit
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        - WWWUSER
        - WWWGROUP
    image: sail-8.0/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '443:443'
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      WWWGROUP: '${WWWGROUP:-1000}'
    volumes:
      - 'sail-apache:/var/www/.bash_history'
      - './sites:/var/www/html'
      - './conf/apache/vhosts:/etc/apache2/sites-enabled'
      - './conf/apache/conf-available:/etc/apache2/conf-available'
      - './conf/php:/usr/local/etc/php'
    networks:
      - sail
    depends_on:
      - mysql
      - redis
#  caddy:
#    image: caddy:latest
#    restart: unless-stopped
#    ports:
#      - '${APP_PORT:-80}:80'
#      - '443:443'
#    volumes:
#      - './caddy:/etc/caddy'
#      - sailcaddy:/data
#      - sailcaddy:/config
#    networks:
#      - sail
  mysql:
    image: mariadb:${MARIA_VERSION}
    command: --max_allowed_packet=256M --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - './data/db:/var/lib/mysql'
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - sail
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sail-redis:/data'
    networks:
      - sail
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
networks:
  sail:
    driver: bridge
volumes:
#  sailmysql:
#    driver: local
  sail-apache:
    driver: local
  sail-redis:
    driver: local
#  sailcaddy:
#    driver: local