FROM ubuntu:21.10

LABEL maintainer="Taylor Otwell"

ARG WWWGROUP
ARG NODE_VERSION=16

WORKDIR /var/www/html

ENV DEBIAN_FRONTEND noninteractive
ENV TZ=UTC

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update \
    && apt-get install -y gnupg gosu curl ca-certificates zip unzip git supervisor sqlite3 libcap2-bin libpng-dev python2 \
    && mkdir -p ~/.gnupg \
    && chmod 600 ~/.gnupg \
    && echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf \
    && apt-key adv --homedir ~/.gnupg --keyserver hkps://keyserver.ubuntu.com --recv-keys 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C \
    && echo "deb https://ppa.launchpadcontent.net/ondrej/php/ubuntu impish main" > /etc/apt/sources.list.d/ppa_ondrej_php.list
RUN apt-get update
RUN apt-get install -y php8.0 php8.0-cli php8.0-dev \
       php8.0-pgsql php8.0-sqlite3 php8.0-gd \
       php8.0-curl php8.0-memcached php8.0-imagick \
       php8.0-imap php8.0-mysql php8.0-mbstring \
       php8.0-xml php8.0-zip php8.0-bcmath php8.0-soap \
       php8.0-intl php8.0-readline php8.0-pcov \
       php8.0-msgpack php8.0-igbinary php8.0-ldap \
       php8.0-redis php8.0-swoole php8.0-xdebug
RUN php -r "readfile('https://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer \
    && curl -sL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g npm \
    && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list \
    && apt-get update \
    && apt-get install -y yarn \
    && apt-get install -y mysql-client \
    && apt-get install -y postgresql-client \
    && apt-get -y autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN update-alternatives --set php /usr/bin/php8.0

RUN setcap "cap_net_bind_service=+ep" /usr/bin/php8.0

RUN curl -LJO https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64 \
    && chmod +x mhsendmail_linux_amd64 \
    && mv mhsendmail_linux_amd64 /usr/local/bin/mhsendmail

RUN echo "max_execution_time=0\n" \
"max_input_time=-1\n" \
"post_max_size=1G\n" \
"upload_max_filesize=512M\n" \
"memory_limit=2048M\n" \
"sendmail_path=/usr/local/bin/mhsendmail\n" | tee "/etc/php/8.0/apache2/conf.d/100-php.ini"

RUN apt-get update \
    && apt-get install -y apache2

RUN apt update && apt install libapache2-mod-php8.0

RUN a2enmod ssl deflate php8.0 rewrite

RUN echo "AddDefaultCharset UTF-8 \n" \
"<FilesMatch \.php$> \n" \
"    SetHandler application/x-httpd-php \n" \
"</FilesMatch> \n" \
"DirectoryIndex disabled \n" \
"DirectoryIndex index.php index.html \n" \
"<Directory /var/www/> \n" \
"    Options -Indexes \n" \
"    AllowOverride All \n" \
"</Directory> \n" | tee "/etc/apache2/conf-available/docker-php.conf"
RUN a2enconf docker-php

#RUN echo "AddDefaultCharset UTF-8
#<FilesMatch \.php$>
#    SetHandler application/x-httpd-php
#</FilesMatch>
#
#DirectoryIndex disabled
#DirectoryIndex index.php index.html
#
#<Directory /var/www/>
#    Options -Indexes
#    AllowOverride All
#</Directory>" | tee "/etc/apache2/conf-available/docker-php.conf"
#RUN a2enconf docker-php

COPY apache-foreground /usr/local/bin/apache-foreground
RUN chmod +x /usr/local/bin/apache-foreground
#CMD ["apache-foreground"]

RUN groupadd --force -g $WWWGROUP sail
RUN useradd -ms /bin/bash --no-user-group -g $WWWGROUP -u 1337 sail
RUN usermod -aG www-data sail

COPY start-container /usr/local/bin/start-container
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY php.ini /etc/php/8.0/cli/conf.d/99-sail.ini

RUN chmod +x /usr/local/bin/start-container

EXPOSE 80 443

ENTRYPOINT ["start-container"]
